
- The os module has a perfect method to list files in a directory.
- Pandas json normalize could work here but is not necessary to convert the JSON data to a dataframe.
- You may need a nested for-loop to access each sale!
- We've put a lot of time into creating the structure of this repository, and it's a good example for future projects.  In the file functions_variables.py, there is an example function that you can import and use.  If you have any variables, functions or classes that you want to make, they can be put in the functions_variables.py file and imported into a notebook.  Note that only .py files can be imported into a notebook. If you want to import everything from a .py file, you can use the following:
```python
from functions_variables import *
```
If you just import functions_variables, then each object from the file will need to be prepended with "functions_variables"\
Using this .py file will keep your notebooks very organized and make it easier to reuse code between notebooks.

In [1]:
# (this is not an exhaustive list of libraries)
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import os
import json
from pprint import pprint

from modules.JSONFramer import JSONFramer

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [2]:
JSONFramer = JSONFramer('../data')
df = JSONFramer.frame()
df.reset_index(drop=True, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8159 entries, 0 to 8158
Data columns (total 45 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   branding_name          7910 non-null   object
 1   baths                  7980 non-null   float64
 2   baths_1qtr             0 non-null      object
 3   baths_3qr              0 non-null      object
 4   baths_full             7311 non-null   object
 5   baths_half             2281 non-null   object
 6   beds                   7504 non-null   object
 7   garage                 4448 non-null   object
 8   lot_sqft               6991 non-null   object
 9   name                   0 non-null      object
 10  sold_date              8159 non-null   object
 11  sold_price             6716 non-null   object
 12  sqft                   7323 non-null   object
 13  stories                6260 non-null   object
 14  sub_type               1427 non-null   object
 15  type                   8125 non-null   object
 16  year_built             7316 non-null   object
 17  is_coming_soon         0 non-null      object
 18  is_contingent          0 non-null      object
 19  is_for_rent            0 non-null      object
 20  is_foreclosure         42 non-null     object
 21  is_new_construction    0 non-null      object
 22  is_new_listing         7752 non-null   object
 23  is_pending             0 non-null      object
 24  is_plan                0 non-null      object
 25  is_price_reduced       2484 non-null   object
 26  is_subdivision         0 non-null      object
 27  last_update_date       8125 non-null   object
 28  show_contact_an_agent  8159 non-null   bool
 29  list_date              7752 non-null   object
 30  list_price             7721 non-null   object
 31  listing_id             7752 non-null   object
 32  city                   8154 non-null   object
 33  lat                    7909 non-null   object
 34  lon                    7909 non-null   object
 35  line                   8144 non-null   object
 36  postal_code            8159 non-null   object
 37  state                  8159 non-null   object
 38  state_code             8159 non-null   object
 39  open_houses            0 non-null      object
 40  price_reduced_amount   2484 non-null   object
 41  brand_name             7673 non-null   object
 42  property_id            8159 non-null   object
 43  status                 8159 non-null   object
 44  tags                   7638 non-null   object
dtypes: bool(1), float64(1), object(43)
memory usage: 2.7+ MB

In [3]:
#count unique property ids
df['property_id'].nunique()
#1795 unique property_ids in a dataframe of 8159 rows indicates that row duplication exists for each property

1795

In [4]:
#display df sorted by 'property_id' column to visually inspect the data
df.sort_values(by=['property_id']).head(6)
#Quick check shows that multiple values for 'branding_name' column exist for each property_id

,branding_name,baths,baths_1qtr,baths_3qr,baths_full,baths_half,beds,garage,lot_sqft,name,sold_date,sold_price,sqft,stories,sub_type,type,year_built,is_coming_soon,is_contingent,is_for_rent,is_foreclosure,is_new_construction,is_new_listing,is_pending,is_plan,is_price_reduced,is_subdivision,last_update_date,show_contact_an_agent,list_date,list_price,listing_id,city,lat,lon,line,postal_code,state,state_code,open_houses,price_reduced_amount,brand_name,property_id,status,tags
5404,Compass,3.0,None,None,3.0,NaN,3.0,5.0,43560,None,2023-12-15,925000,2980.0,1.0,None,single_family,1978.0,None,None,None,None,None,False,None,None,None,None,2023-12-15T21:25:24Z,True,2023-09-25T16:20:27.000000Z,925000,2959966417,Carson City,39.093819,-119.79112,3527 Arcadia Dr,89705,Nevada,NV,None,NaN,basic_opt_in,1003442504,sold,"[community_outdoor_space, energy_efficient, fa..."
476,"Sell Your Home Services, Inc.",3.0,None,None,3.0,None,4.0,2.0,95832.0,None,2023-12-22,625600,2136.0,1.0,None,single_family,1996.0,None,None,None,None,None,False,None,None,None,None,2023-12-23T09:05:36Z,True,2023-11-20T16:22:33.000000Z,600000.0,2961854149,Phoenix,33.804177,-112.056055,35033 N 12th St,85086,Arizona,AZ,None,NaN,basic_opt_in,1007849822,sold,"[single_story, garage_1_or_more, garage_2_or_m..."
647,Cooper Premier Properties Llc,3.0,None,None,3.0,None,4.0,2.0,95832.0,None,2023-12-22,625600,2136.0,1.0,None,single_family,1996.0,None,None,None,None,None,False,None,None,None,None,2023-12-23T09:05:36Z,True,2023-11-20T16:22:33.000000Z,600000.0,2961854149,Phoenix,33.804177,-112.056055,35033 N 12th St,85086,Arizona,AZ,None,NaN,basic_opt_in,1007849822,sold,"[single_story, garage_1_or_more, garage_2_or_m..."
558,My Home Group Real Estate,3.0,None,None,3.0,None,4.0,2.0,95832.0,None,2023-12-22,625600,2136.0,1.0,None,single_family,1996.0,None,None,None,None,None,False,None,None,None,None,2023-12-23T09:05:36Z,True,2023-11-20T16:22:33.000000Z,600000.0,2961854149,Phoenix,33.804177,-112.056055,35033 N 12th St,85086,Arizona,AZ,None,NaN,basic_opt_in,1007849822,sold,"[single_story, garage_1_or_more, garage_2_or_m..."
599,Keller Williams Realty Sonoran Living,3.0,None,None,3.0,None,4.0,2.0,95832.0,None,2023-12-22,625600,2136.0,1.0,None,single_family,1996.0,None,None,None,None,None,False,None,None,None,None,2023-12-23T09:05:36Z,True,2023-11-20T16:22:33.000000Z,600000.0,2961854149,Phoenix,33.804177,-112.056055,35033 N 12th St,85086,Arizona,AZ,None,NaN,basic_opt_in,1007849822,sold,"[single_story, garage_1_or_more, garage_2_or_m..."
517,"Weichert, Realtors - Courtney Valleywide",3.0,None,None,3.0,None,4.0,2.0,95832.0,None,2023-12-22,625600,2136.0,1.0,None,single_family,1996.0,None,None,None,None,None,False,None,None,None,None,2023-12-23T09:05:36Z,True,2023-11-20T16:22:33.000000Z,600000.0,2961854149,Phoenix,33.804177,-112.056055,35033 N 12th St,85086,Arizona,AZ,None,NaN,basic_opt_in,1007849822,sold,"[single_story, garage_1_or_more, garage_2_or_m..."

In [5]:
#check shape of the df after dropping duplicated 'branding_name' column and unhashable 'tags' column
temp_dataframe = df.drop(columns =['branding_name','tags'])
temp_dataframe.drop_duplicates().shape
#1795 rows is same number as unique property ids, therefore eliminating the branding_name column will remove duplicates

(1795, 43)

In [6]:
# #Note: the 'tags' column was checked for duplication by converting the list type of each value to a string and then applying '.drop_duplicates'

# def tas_to_string...

# string_data = all_data
# string_data.loc[:, 'tags'] = string_data['tags'].apply(lambda x: tags_to_string(x))

# string_data.drop_duplicates().info()

# # No duplication was found

In [7]:
#check to see how many unique 'branding_name' values there are (just in case there were only a few and we could keep this column)
len(df['branding_name'].unique())
#As expected, there are too many (172) so the column can be dropped

172

**-Drop Columns:**

In [8]:
#drop the 'branding_name' column 
#also drop all columns with 0 non-null values including the following:
df = df.drop(columns = ['branding_name', 'baths_1qtr', 'baths_3qr', 'name', 'is_coming_soon', 'is_contingent', 'is_for_rent', 'is_new_construction', 'is_pending', 'is_plan', 'is_subdivision', 'open_houses'])

# df = dataframe.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8159 entries, 0 to 8158
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   baths                  7980 non-null   float64
 1   baths_full             7311 non-null   object
 2   baths_half             2281 non-null   object
 3   beds                   7504 non-null   object
 4   garage                 4448 non-null   object
 5   lot_sqft               6991 non-null   object
 6   sold_date              8159 non-null   object
 7   sold_price             6716 non-null   object
 8   sqft                   7323 non-null   object
 9   stories                6260 non-null   object
 10  sub_type               1427 non-null   object
 11  type                   8125 non-null   object
 12  year_built             7316 non-null   object
 13  is_foreclosure         42 non-null     object
 14  is_new_listing         7752 non-null   object
 15  is_price_reduced       2484 non-null   object
 16  last_update_date       8125 non-null   object
 17  show_contact_an_agent  8159 non-null   bool
 18  list_date              7752 non-null   object
 19  list_price             7721 non-null   object
 20  listing_id             7752 non-null   object
 21  city                   8154 non-null   object
 22  lat                    7909 non-null   object
 23  lon                    7909 non-null   object
 24  line                   8144 non-null   object
 25  postal_code            8159 non-null   object
 26  state                  8159 non-null   object
 27  state_code             8159 non-null   object
 28  price_reduced_amount   2484 non-null   object
 29  brand_name             7673 non-null   object
 30  property_id            8159 non-null   object
 31  status                 8159 non-null   object
 32  tags                   7638 non-null   object
dtypes: bool(1), float64(1), object(31)
memory usage: 2.0+ MB

**-Drop rows where target column is null:**

In [9]:
#Because our model's target variable is 'sold_price', we can drop all rows where this is null
df.dropna(subset=['sold_price'], inplace=True)
df.shape

(6716, 33)

**-Encode 'tags' in columns:**

In [10]:
#we need to explode and one-hot-code the 'tags' column
#(this needs to be done before dropping duplicated as the list data type for tags values is unhashable)

In [11]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
s = df['tags'].apply(lambda x: x if x is not None else [])
binarized_tags = pd.DataFrame(mlb.fit_transform(s),columns=mlb.classes_, index=df.index)

binarized_tags.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6716 entries, 30 to 8158
Columns: 152 entries, baseball to wrap_around_porch
dtypes: int32(152)
memory usage: 3.9 MB

In [12]:
df = df.merge(binarized_tags, left_index=True, right_index=True).drop(columns='tags')
df = df.drop_duplicates()

In [13]:
df.columns

Index(['baths', 'baths_full', 'baths_half', 'beds', 'garage', 'lot_sqft',
       'sold_date', 'sold_price', 'sqft', 'stories',
       ...
       'views', 'volleyball', 'washer_dryer', 'water_view', 'waterfront',
       'well_water', 'white_kitchen', 'wine_cellar', 'wooded_land',
       'wrap_around_porch'],
      dtype='object', length=184)

In [14]:
#Drop 'tags' column
#Perform count for all newly created binary tag columns / by total row count
#Drop all binary tag columns that are represented in less that [10%?] of the data



binarized_tags_dict = (df.loc[:, mlb.classes_.tolist()].sum()/df.shape[0]).to_dict()

binarized_tags_list = []

for key in binarized_tags_dict.keys():
    if binarized_tags_dict[key] < 0.05:
        binarized_tags_list.append(key)

binarized_tags_list

['baseball',
 'basketball',
 'basketball_court',
 'beach',
 'beautiful_backyard',
 'big_bathroom',
 'boat_dock',
 'cathedral_ceiling',
 'clubhouse',
 'coffer_ceiling',
 'community_boat_facilities',
 'community_center',
 'community_clubhouse',
 'community_elevator',
 'community_golf',
 'community_gym',
 'community_horse_facilities',
 'community_park',
 'community_spa_or_hot_tub',
 'community_tennis_court',
 'courtyard_entry',
 'cul_de_sac',
 'den_or_office',
 'detached_guest_house',
 'dual_master_bedroom',
 'efficient',
 'elevator',
 'exposed_brick',
 'fenced_courtyard',
 'first_floor_master_bedroom',
 'fixer_upper',
 'fruit_trees',
 'furniture',
 'game_room',
 'gated_community',
 'golf_course',
 'golf_course_lot_or_frontage',
 'golf_course_view',
 'gourmet_kitchen',
 'granite_kitchen',
 'greenbelt',
 'greenhouse',
 'guest_house',
 'guest_parking',
 'handicap_access',
 'hill_or_mountain_view',
 'hoa',
 'horse_facilities',
 'indoor_basketball_court',
 'investment_opportunity',
 'jack_and_jill_bathroom',
 'kitchen_island',
 'lake',
 'lake_view',
 'large_kitchen',
 'large_porch',
 'library',
 'low_hoa',
 'maintenance',
 'marina',
 'master_bathroom',
 'master_suite',
 'media_room',
 'medicalcare',
 'mountain_view',
 'no_hoa',
 'ocean_view',
 'open_house',
 'open_kitchen',
 'outbuilding',
 'outdoor_kitchen',
 'pets_allowed',
 'playground',
 'pond',
 'private_backyard',
 'private_bathroom',
 'private_courtyard',
 'private_parking',
 'river_access',
 'river_view',
 'rv_or_boat_parking',
 'rv_parking',
 'screen_porch',
 'security',
 'senior_community',
 'smart_homes',
 'soccer',
 'solar_panels',
 'solar_system',
 'spa_or_hot_tub',
 'storm_shelter',
 'tennis',
 'tennis_court',
 'theater_room',
 'two_kitchen',
 'two_master_suites',
 'vaulted_ceiling',
 'volleyball',
 'water_view',
 'waterfront',
 'well_water',
 'white_kitchen',
 'wine_cellar',
 'wooded_land',
 'wrap_around_porch']

In [15]:
df = df.drop(columns=binarized_tags_list)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1475 entries, 30 to 8038
Data columns (total 79 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   baths                        1443 non-null   float64
 1   baths_full                   1329 non-null   object
 2   baths_half                   434 non-null    object
 3   beds                         1367 non-null   object
 4   garage                       764 non-null    object
 5   lot_sqft                     1275 non-null   object
 6   sold_date                    1475 non-null   object
 7   sold_price                   1475 non-null   object
 8   sqft                         1331 non-null   object
 9   stories                      1118 non-null   object
 10  sub_type                     259 non-null    object
 11  type                         1471 non-null   object
 12  year_built                   1329 non-null   object
 13  is_foreclosure               6 non-null      object
 14  is_new_listing               1412 non-null   object
 15  is_price_reduced             444 non-null    object
 16  last_update_date             1471 non-null   object
 17  show_contact_an_agent        1475 non-null   bool
 18  list_date                    1412 non-null   object
 19  list_price                   1412 non-null   object
 20  listing_id                   1412 non-null   object
 21  city                         1474 non-null   object
 22  lat                          1435 non-null   object
 23  lon                          1435 non-null   object
 24  line                         1474 non-null   object
 25  postal_code                  1475 non-null   object
 26  state                        1475 non-null   object
 27  state_code                   1475 non-null   object
 28  price_reduced_amount         444 non-null    object
 29  brand_name                   1397 non-null   object
 30  property_id                  1475 non-null   object
 31  status                       1475 non-null   object
 32  basement                     1475 non-null   int32
 33  big_lot                      1475 non-null   int32
 34  big_yard                     1475 non-null   int32
 35  carport                      1475 non-null   int32
 36  central_air                  1475 non-null   int32
 37  central_heat                 1475 non-null   int32
 38  city_view                    1475 non-null   int32
 39  community_outdoor_space      1475 non-null   int32
 40  community_security_features  1475 non-null   int32
 41  community_swimming_pool      1475 non-null   int32
 42  corner_lot                   1475 non-null   int32
 43  dining_room                  1475 non-null   int32
 44  disability_features          1475 non-null   int32
 45  dishwasher                   1475 non-null   int32
 46  energy_efficient             1475 non-null   int32
 47  ensuite                      1475 non-null   int32
 48  family_room                  1475 non-null   int32
 49  farm                         1475 non-null   int32
 50  fenced_yard                  1475 non-null   int32
 51  fireplace                    1475 non-null   int32
 52  floor_plan                   1475 non-null   int32
 53  forced_air                   1475 non-null   int32
 54  front_porch                  1475 non-null   int32
 55  garage_1_or_more             1475 non-null   int32
 56  garage_2_or_more             1475 non-null   int32
 57  garage_3_or_more             1475 non-null   int32
 58  groundscare                  1475 non-null   int32
 59  hardwood_floors              1475 non-null   int32
 60  high_ceiling                 1475 non-null   int32
 61  laundry_room                 1475 non-null   int32
 62  master_bedroom               1475 non-null   int32
 63  modern_kitchen               1475 non-null   int32
 64  new_roof                     1475 non-null   int32
 65  open_floor_plan              1475 non-null   int32
 66  park                         1475 non-null   int32
 67  ranch                        1475 non-null   int32
 68  recreation_facilities        1475 non-null   int32
 69  rental_property              1475 non-null   int32
 70  shopping                     1475 non-null   int32
 71  single_story                 1475 non-null   int32
 72  swimming_pool                1475 non-null   int32
 73  trails                       1475 non-null   int32
 74  two_or_more_stories          1475 non-null   int32
 75  updated_kitchen              1475 non-null   int32
 76  view                         1475 non-null   int32
 77  views                        1475 non-null   int32
 78  washer_dryer                 1475 non-null   int32
dtypes: bool(1), float64(1), int32(47), object(30)
memory usage: 641.0+ KB

**-Fill N/A Values**

In [17]:
#fill N/A values with zeros for 'baths_half', 'garage', price_reduced_amount
df.update(df[['baths_full','baths_half', 'garage', 'price_reduced_amount']].fillna(0))

In [18]:
#fill N/A values with 'False' for 'is_price_reduced'
df['is_price_reduced'].fillna(False, inplace=True)

**-Drop more unecessary Columns**

In [19]:
#drop 'sub-type' column as it appears to be either missing or very similar to type in most instances
df.drop(columns='sub_type', inplace=True)

In [20]:
#We can probably drop 'last_update' column as I assume it has to do with website or realtor activity
df.drop(columns='last_update_date', inplace=True)

In [21]:
#Only False values for this column so we can drop it
#It might be the case that None type should be 'True' but I don't think we have enough info to make this inference
df.drop(columns='is_new_listing', inplace=True)

In [22]:
#Not obvious what brand name is - I suggest we drop but we could also just try modelling with it left in
df.drop(columns='brand_name', inplace=True)

In [23]:
#status is always sold so we can drop this
df.drop(columns='status', inplace=True)

**-Change Boolean values to Binary**

In [24]:
df.drop(columns='show_contact_an_agent', inplace=True)

In [25]:
#Do we want to drop the foreclosure column because so few data points exist?
df.drop(columns='is_foreclosure', inplace=True)
#Alternatively we can just fill thse values null values with False

In [26]:
df[df['beds'].isna()].head()

,baths,baths_full,baths_half,beds,garage,lot_sqft,sold_date,sold_price,sqft,stories,type,year_built,is_price_reduced,list_date,list_price,listing_id,city,lat,lon,line,postal_code,state,state_code,price_reduced_amount,property_id,basement,big_lot,big_yard,carport,central_air,central_heat,city_view,community_outdoor_space,community_security_features,community_swimming_pool,corner_lot,dining_room,disability_features,dishwasher,energy_efficient,ensuite,family_room,farm,fenced_yard,fireplace,floor_plan,forced_air,front_porch,garage_1_or_more,garage_2_or_more,garage_3_or_more,groundscare,hardwood_floors,high_ceiling,laundry_room,master_bedroom,modern_kitchen,new_roof,open_floor_plan,park,ranch,recreation_facilities,rental_property,shopping,single_story,swimming_pool,trails,two_or_more_stories,updated_kitchen,view,views,washer_dryer
40,0.0,0.0,0.0,NaN,0.0,3397680.0,2024-01-12,370000,NaN,NaN,land,NaN,False,2022-09-02T18:18:05.000000Z,395000.0,2947407483,Montgomery,32.155112,-86.220291,3180 E Old Hayneville Rd,36105,Alabama,AL,0.0,9371305836,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
251,0.0,0.0,0.0,NaN,0.0,5663.0,2024-01-11,76000,NaN,NaN,land,NaN,False,2023-07-27T19:18:01.000000Z,76000.0,2958104378,Little Rock,NaN,NaN,202 Fletcher Ridge Dr,72223,Arkansas,AR,0.0,9934955122,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
262,0.0,0.0,0.0,NaN,0.0,534481.0,2024-01-08,453990,NaN,NaN,land,NaN,False,2023-07-01T13:50:14.000000Z,490800.0,2957307707,Little Rock,NaN,NaN,00012 Denny Rd,72223,Arkansas,AR,0.0,9118590787,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
269,0.0,0.0,0.0,NaN,0.0,23522.0,2024-01-05,107500,NaN,NaN,land,NaN,False,2023-09-08T17:46:32.000000Z,124900.0,2959499539,Little Rock,34.772842,-92.481706,120 Sezanne Ct,72223,Arkansas,AR,0.0,7567034580,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
274,NaN,0.0,0.0,NaN,0.0,8276.0,2024-01-05,325000,4344.0,2.0,multi_family,1930.0,False,2023-11-04T21:17:00.000000Z,325000.0,2961369623,Little Rock,34.725859,-92.29413,2405 S Battery St,72206,Arkansas,AR,40000.0,7526785866,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0

In [50]:
#fill N/A values with zeros for 'baths','beds', 'sqft', 'stories', 'year_built' columns where value in 'type' column == land
# df.update(df[['baths','beds', 'sqft', 'stories', 'year_built']].fillna(0))
# df.loc[df['type'].isin(['land'])]

#Not working...
# df.update(df.loc[df['type'].isin(['land'])][['baths', 'beds', 'sqft', 'stories', 'year_built']].fillna(0, inplace=True))
# df.update(df.loc[df['type']=='land'][['baths', 'beds', 'sqft', 'stories', 'year_built']].fillna(0, inplace=True))

#Works!
df.update(df.loc[df['type'].isin(['land'])][['baths', 'beds', 'sqft', 'stories', 'year_built']].fillna(0))

In [51]:
print(df[df['beds'].isna()].shape)
df[df['beds'].isna()]

(37, 72)

,baths,baths_full,baths_half,beds,garage,lot_sqft,sold_date,sold_price,sqft,stories,type,year_built,is_price_reduced,list_date,list_price,listing_id,city,lat,lon,line,postal_code,state,state_code,price_reduced_amount,property_id,basement,big_lot,big_yard,carport,central_air,central_heat,city_view,community_outdoor_space,community_security_features,community_swimming_pool,corner_lot,dining_room,disability_features,dishwasher,energy_efficient,ensuite,family_room,farm,fenced_yard,fireplace,floor_plan,forced_air,front_porch,garage_1_or_more,garage_2_or_more,garage_3_or_more,groundscare,hardwood_floors,high_ceiling,laundry_room,master_bedroom,modern_kitchen,new_roof,open_floor_plan,park,ranch,recreation_facilities,rental_property,shopping,single_story,swimming_pool,trails,two_or_more_stories,updated_kitchen,view,views,washer_dryer
274,NaN,0.0,0.0,NaN,0.0,8276.0,2024-01-05,325000,4344.0,2.0,multi_family,1930.0,False,2023-11-04T21:17:00.000000Z,325000.0,2961369623,Little Rock,34.725859,-92.29413,2405 S Battery St,72206,Arkansas,AR,40000.0,7526785866,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
456,0.0,0.0,0.0,NaN,0.0,46035.0,2023-12-26,1900000,NaN,NaN,multi_family,1949.0,False,2023-09-04T13:24:48.000000Z,2200000.0,2959337342,Phoenix,33.459104,-112.031727,2316 E Roosevelt St,85006,Arizona,AZ,40000.0,1301214169,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
480,0.0,0.0,0.0,NaN,0.0,NaN,2023-12-22,485000,NaN,NaN,multi_family,1950.0,False,2023-06-28T01:07:26.000000Z,495000.0,2957128899,Phoenix,33.397853,-112.089102,5237 S 14th Ave,85041,Arizona,AZ,64000.0,2073480300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1093,NaN,0.0,0.0,NaN,0.0,7405.0,2024-01-05,227000,4512.0,NaN,multi_family,1880.0,False,2023-08-29T17:33:03.000000Z,275000.0,2959182819,Hartford,41.760903,-72.689597,103 Babcock St,06106,Connecticut,CT,20000.0,4104926733,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1107,NaN,0.0,0.0,NaN,0.0,20038.0,2023-12-22,1200000,32106.0,NaN,multi_family,1920.0,False,2023-03-27T14:26:49.000000Z,2350000.0,2953936748,Hartford,41.766034,-72.709751,527 Farmington Ave,06105,Connecticut,CT,0.0,4750734663,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1739,NaN,0.0,0.0,NaN,0.0,11252.0,2024-01-08,410000,NaN,1.0,multi_family,1920.0,False,2023-12-04T15:17:21.000000Z,425000.0,2962208171,Atlanta,33.725041,-84.409732,675 Mayland Ave SW,30310,Georgia,GA,0.0,6349581711,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0
2347,0.0,0.0,0.0,NaN,0.0,NaN,2023-12-27,27065000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,NaN,NaN,3501 Old Jacksonville Rd,62711,Illinois,IL,0.0,9627477899,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2366,0.0,0.0,0.0,NaN,0.0,NaN,2023-08-14,119900.0,NaN,NaN,condo,NaN,False,None,NaN,None,Springfield,39.820301,-89.704559,83 Amherst Dr,62702,Illinois,IL,0.0,8559138865,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2367,NaN,0.0,0.0,NaN,0.0,NaN,2023-08-11,359900.0,NaN,NaN,None,NaN,False,None,NaN,None,Springfield,NaN,NaN,4615 Lasalle Ct,62711,Illinois,IL,0.0,9526532270,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2371,0.0,0.0,0.0,NaN,0.0,10925.0,2023-07-24,130000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.760722,-89.703887,416 Yeoman Dr,62704,Illinois,IL,0.0,7566735445,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2372,0.0,0.0,0.0,NaN,0.0,5960.0,2023-07-24,68000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.775775,-89.637265,2237 S 14th St,62703,Illinois,IL,0.0,8487172216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2373,0.0,0.0,0.0,NaN,0.0,43560.0,2023-07-24,142000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.775651,-89.582633,3532 E State Route 29,62712,Illinois,IL,0.0,8629721141,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2374,0.0,0.0,0.0,NaN,0.0,11436.0,2023-07-24,207000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.792227,-89.691555,933 Westview Dr,62704,Illinois,IL,0.0,8907724492,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2375,0.0,0.0,0.0,NaN,0.0,10466.0,2023-07-24,346001.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.774194,-89.724453,2108 Dubsdread Dr,62711,Illinois,IL,0.0,7311351941,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2376,0.0,0.0,0.0,NaN,0.0,9614.0,2023-07-24,275000.0,NaN,NaN,other,NaN,False,None,NaN,None,Springfield,39.78819,-89.651613,1201 S 4th St,62703,Illinois,IL,0.0,9515169963,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2379,0.0,0.0,0.0,NaN,0.0,5759.0,2023-07-21,10000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.814596,-89.66286,565 W Elliott Ave,62702,Illinois,IL,0.0,7222439436,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2380,0.0,0.0,0.0,NaN,0.0,5759.0,2023-07-21,10000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.814594,-89.663002,565 W Elliott Ave,62702,Illinois,IL,0.0,8739121995,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2381,0.0,0.0,0.0,NaN,0.0,6534.0,2023-07-21,230000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.761837,-89.728436,3913 Marryat Dr,62711,Illinois,IL,0.0,7237341779,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2382,0.0,0.0,0.0,NaN,0.0,15000.0,2023-07-21,475000.0,NaN,NaN,single_family,NaN,False,None,NaN,None,Springfield,39.703407,-89.702628,2804 Castlerock Rdg,62711,Illinois,IL,0.0,8268080483,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2551,NaN,0.0,0.0,NaN,0.0,NaN,2023-09-27,162000,NaN,NaN,None,NaN,False,None,NaN,None,Indianapolis,NaN,NaN,4030 N Edmondson Ave,46226,Indiana,IN,0.0,9350399869,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2557,NaN,0.0,0.0,NaN,0.0,NaN,2023-08-31,294988,NaN,NaN,None,NaN,False,None,NaN,None,Indianapolis,NaN,NaN,4736 Topaz Pointe Blvd,46235,Indiana,IN,0.0,9333826731,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2558,0.0,0.0,0.0,NaN,0.0,NaN,2023-08-28,676860,NaN,NaN,other,NaN,False,None,NaN,None,Indianapolis,NaN,NaN,7428 Glen Park Way,46259,Indiana,IN,0.0,9654204496,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2561,NaN,0.0,0.0,NaN,0.0,NaN,2023-08-23,349990,NaN,NaN,None,NaN,False,None,NaN,None,Indianapolis,NaN,NaN,10715 Mangrove Dr,46239,Indiana,IN,0.0,9013856578,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4375,NaN,0.0,0.0,NaN,0.0,NaN,2024-01-11,690000,NaN,NaN,single_family,1961.0,False,2022-10-08T03:24:32.000000Z,900000,2948706621,Raleigh,35.779021,-78.688667,3811 Marcom St,27606,North Carolina,NC,100000.0,5369653239,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
5640,0.0,0.0,0.0,NaN,0.0,NaN,2023-10-05,656700,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,2897 Katmai Dr # A,43228,Ohio,OH,0.0,9632427826,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5641,0.0,0.0,0.0,NaN,0.0,NaN,2023-10-04,499300,NaN,NaN,single_family,NaN,False,None,NaN,None,Westerville,40.096367,-82.866679,5626 Godetia St,43081,Ohio,OH,0.0,9414271198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5642,0.0,0.0,0.0,NaN,0.0,NaN,2023-10-04,718800,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,2852 Kobuk Dr # A,43228,Ohio,OH,0.0,9280609914,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5647,0.0,0.0,0.0,NaN,0.0,NaN,2023-09-28,550000,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,1204 Hamlet St,43201,Ohio,OH,0.0,9177544469,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5650,0.0,0.0,0.0,NaN,0.0,NaN,2023-09-22,824800,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,2880 Kobuk Dr # A,43228,Ohio,OH,0.0,9303853384,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5654,0.0,0.0,0.0,NaN,0.0,NaN,2023-09-12,748900,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,2876 Kobuk Dr # A,43228,Ohio,OH,0.0,9531561471,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5656,0.0,0.0,0.0,NaN,0.0,NaN,2023-09-12,1059800,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,2844 Kobuk Dr # A,43228,Ohio,OH,0.0,9945242835,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5782,0.0,0.0,0.0,NaN,0.0,NaN,2023-09-08,792600,NaN,NaN,condo,NaN,False,None,NaN,None,Columbus,NaN,NaN,2909 Katmai Dr # A,43228,Ohio,OH,0.0,9637850403,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6829,0.0,0.0,0.0,NaN,0.0,NaN,2023-09-01,710000,NaN,NaN,single_family,NaN,False,None,NaN,None,Nashville,NaN,NaN,2122B 12th Ave N,37208,Tennessee,TN,0.0,9241050124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6832,0.0,0.0,0.0,NaN,0.0,NaN,2023-07-27,534900,NaN,NaN,condo,NaN,False,None,NaN,None,Nashville,36.146606,-86.816841,303 31st Ave N Apt 206,37203,Tennessee,TN,0.0,9036979390,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6839,0.0,0.0,0.0,NaN,0.0,86249.0,2023-07-21,170000,NaN,1.0,mobile,NaN,False,None,NaN,None,Joelton,36.288843,-86.918623,6000 Marrowbone Lake Rd,37080,Tennessee,TN,0.0,7350121055,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7547,NaN,0.0,0.0,NaN,0.0,8316.0,2024-01-11,550000,2304.0,NaN,multi_family,1962.0,False,2023-06-23T18:24:26.000000Z,575000,2957022448,Olympia,47.019055,-122.886233,3208 Hawthorne Pl SE Unit 10,98501,Washington,WA,20000.0,1465929999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
7618,NaN,0.0,0.0,NaN,0.0,9549.0,2023-12-27,425000,1920.0,NaN,multi_family,1980.0,False,2023-11-10T21:20:16.000000Z,425000,2961539260,Olympia,47.064723,-122.743852,1433 Lapush Way NE Unit A,98516,Washington,WA,0.0,1479494802,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,1,0,0

**-Time on Market, Month sold, Month listed Columns**

In [29]:
#We could pull just the month (and/or year) from the 'sold date' (and/or list date) columns to make 'month listed', 'month sold' columns
#We could also create a 'time on market' from the 'sold date' and 'month listed' columns

**-Drop foreclosure Column?**

**-Create Mean House Sale Value by City Column**

In [30]:
#(based on Samson's suggestion)
#Drop location (city, state) columns
#create new column that lists the mean house sale value based on the row's corresponding city

**-Normalize Data**

In [31]:
#Normalize, scaler?

At this point, ensure that you have all sales in a dataframe.
- Is each cell one value, or do some cells have lists?
- Maybe the "tags" will help create some features.
- What are the data types of each column?
- Some sales may not actually include the sale price.  These rows should be dropped.
- Some sales don't include the property type.
- There are a lot of None values.  Should these be dropped or replaced with something?

In [32]:
# load and concatenate data here
# drop or replace values as necessary

Consider the fact that with tags, there are a lot of categorical variables.
- How many columns would we have if we OHE tags, city and state?
- Perhaps we can get rid of tags that have a low frequency.

In [33]:
# OHE categorical variables here
# tags will have to be done manually

- Sales will vary drastically between cities and states.  Is there a way to keep information about which city it is without OHE such as using central tendency?
- Could we label encode or ordinal encode?  Yes, but this may have undesirable effects, giving nominal data ordinal values.
- If you replace cities or states with numerical values, make sure that the data is split so that we don't leak data into the training selection. This is a great time to train test split. Compute on the training data, and join these values to the test data
- Drop columns that aren't needed.
- Don't keep the list price because it will be too close to the sale price.

In [34]:
# perform train test split here
# do something with state and city
# drop any other not needed columns

**STRETCH**

- You're not limited to just using the data provided to you. Think/ do some research about other features that might be useful to predict housing prices. 
- Can you import and join this data? Make sure you do any necessary preprocessing and make sure it is joined correctly.
- Example suggestion: could mortgage interest rates in the year of the listing affect the price?

In [35]:
# import, join and preprocess new data here

Remember all of the EDA that you've been learning about?  Now is a perfect time for it!
- Look at distributions of numerical variables to see the shape of the data and detect outliers.
- Scatterplots of a numerical variable and the target go a long way to show correlations.
- A heatmap will help detect highly correlated features, and we don't want these.
- Is there any overlap in any of the features? (redundant information, like number of this or that room...)

In [36]:
# perform EDA here

Now is a great time to scale the data and save it once it's preprocessed.
- You can save it in your data folder, but you may want to make a new `processed/` subfolder to keep it organized